[package]
name = "hamie/steal-a-pirate"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ByteNetMax = "elitriare/bytenet-max@0.1.9"

Charm = "littensy/charm@0.10.0"

Fusion = "elttob/fusion@0.3.0"
Observers = "sleitnick/observers@^0.3.4"

Streamable = "sleitnick/streamable@1.2.4"
Signal = "sleitnick/signal@2.0.3"

TaskQueue = "sleitnick/task-queue@1.0.0"
Trove = "sleitnick/trove@1.5.0"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"