local SharedRaritiesData = {}

SharedRaritiesData.Info = {
	Common = { PrimaryColor = Color3.fromRGB(166, 157, 54), CharacterHighlight = false },
	Uncommon = { PrimaryColor = Color3.fromRGB(28, 166, 33), CharacterHighlight = false },
	Rare = { PrimaryColor = Color3.fromRGB(34, 98, 166), CharacterHighlight = false },
	Epic = { PrimaryColor = Color3.fromRGB(150, 28, 171), CharacterHighlight = true },
	Legendary = { PrimaryColor = Color3.fromRGB(222, 229, 84), CharacterHighlight = true },
	Mythical = { PrimaryColor = Color3.fromRGB(166, 7, 10), CharacterHighlight = true },
	Unknown = { PrimaryColor = Color3.fromRGB(255, 255, 255), CharacterHighlight = true },
}

return SharedRaritiesData
